
name: '[Callable]: Package - Publish'

on:
  workflow_call:
    inputs:
      download-url:
        type: string
        required: true
        description: |
          Expected URL of the specific package version on the indexing platform.
      upload-url:
        type: string
        required: true
        description: |
          URL of the package index to upload to.
      platform:
        type: string
        default: 'TestPyPI'
        required: false
        description: |
          Platform to publish to; either 'TestPyPI' (default) or 'PyPI'.

jobs:
  package-release-pypi:
    name: ${{ inputs.platform }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.platform }}
      url: ${{ inputs.download-url }}
    permissions:
      id-token: write
    steps:
      - name: 'Download sdist and wheels artifacts'
        uses: actions/download-artifact@v3
        with:
          name: Distribution Package
          path: dist
      - name: 'Upload package'
        uses: pypa/gh-action-pypi-publish@release/v1
        # https://github.com/marketplace/actions/pypi-publish
        with:
          packages-dir: dist
          repository-url: ${{ inputs.upload-url }}
          verify-metadata: true
          verbose: true
          print-hash: true
          skip-existing: false
